version: '2'

services:
  proxy:
    build: nginx/
    restart: always
    container_name: "portainer-proxy"
    ports:
      - "8880:80"
    environment:
      - URL_UTILE:${URL_UTILE}
    networks:
      - local


  portainer:
    image: portainer/portainer:1.22.0
    restart: always
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
    command: --admin-password '$$2y$$05$$BZDHtzwzM1DEgL5pjAePAuoAbX6DknRE3XW3aU6HgBbwYdqwRcj3q' -H unix:///var/run/docker.sock
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data

networks:
  local:
    external:
      name: bridge_e-combox

volumes:
  portainer-data: {}
